# Generated by Django 6.0.3 on 2026-04-07 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='current_level',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='Beginner', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='preferred_study_time',
            field=models.CharField(choices=[('Morning', 'Morning'), ('Afternoon', 'Afternoon'), ('Night', 'Night')], default='Morning', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='availability',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Other', max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='goals',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='student_status',
            field=models.CharField(choices=[('Student', 'Student'), ('Non-Student', 'Non-Student')], default='Student', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='skills_to_learn',
            field=models.ManyToManyField(blank=True, related_name='learners', to='useraccount.skill'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='skills_to_teach',
            field=models.ManyToManyField(blank=True, related_name='teachers', to='useraccount.skill'),
        ),
    ]
