# Generated by Django 6.0.3 on 2026-04-07 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0002_skill_userprofile_current_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='skills_to_learn',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='skills_to_teach',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='student_status',
            field=models.CharField(choices=[('University Student', 'University Student'), ('Final Year Student', 'Final Year Student'), ('Working Professional', 'Working Professional'), ('Non-Student', 'Non-Student')], default='University Student', max_length=30),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='skills_to_learn',
            field=models.TextField(blank=True, help_text='List skills separated by commas'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='skills_to_teach',
            field=models.TextField(blank=True, help_text='List skills separated by commas'),
        ),
    ]
