# Generated by Django 6.0.3 on 2026-04-07 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0003_alter_skill_name_remove_userprofile_skills_to_learn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pics/default.png', upload_to='profile_pics/'),
        ),
    ]
