# Generated by Django 6.0 on 2026-04-08 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0003_alter_userprofile_options_userprofile_created_at_and_more'),
        ('useraccount', '0005_alter_userprofile_options_userprofile_created_at_and_more'),
    ]

    operations = [
    ]
