# Generated by Django 6.0.3 on 2026-04-25 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0007_connection_connectionrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='skills_to_learn',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='skills_to_teach',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='skills_to_learn',
            field=models.ManyToManyField(blank=True, related_name='users_learning', to='useraccount.skill'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='skills_to_teach',
            field=models.ManyToManyField(blank=True, related_name='users_teaching', to='useraccount.skill'),
        ),
    ]
