# Generated by Django 6.0.3 on 2026-04-25 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0008_remove_userprofile_skills_to_learn_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='skills_to_learn',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='skills_to_teach',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='skills_to_learn',
            field=models.TextField(blank=True, help_text='List skills separated by commas', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='skills_to_teach',
            field=models.TextField(blank=True, help_text='List skills separated by commas', null=True),
        ),
    ]
