# Generated by Django 6.0 on 2026-04-26 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0009_remove_userprofile_skills_to_learn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='study_partners_count',
            field=models.IntegerField(default=0),
        ),
    ]
