# Generated by Django 6.0.3 on 2026-04-27 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0009_remove_userprofile_skills_to_learn_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='preferred_study_time',
            field=models.CharField(choices=[('Morning', 'Morning'), ('Afternoon', 'Afternoon'), ('Evening', 'Evening'), ('Night', 'Night'), ('Late Night', 'Late Night'), ('Flexible', 'Flexible'), ('Weekend Only', 'Weekend Only'), ('Weekday Only', 'Weekday Only')], default='Morning', max_length=20),
        ),
        migrations.CreateModel(
            name='UserSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('tech', 'Tech / Programming'), ('language', 'Language'), ('general', 'General Skills')], max_length=20)),
                ('skill_type', models.CharField(choices=[('teach', 'I Can Teach'), ('learn', 'I Want to Learn')], max_length=10)),
                ('proficiency_level', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='useraccount.userprofile')),
            ],
            options={
                'ordering': ['skill_type', 'skill_name'],
                'unique_together': {('user_profile', 'skill_name', 'skill_type')},
            },
        ),
    ]
