# Generated by Django 6.0.3 on 2026-04-27 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0010_alter_userprofile_preferred_study_time_userskill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="e.g., 'Google Data Analytics Professional Certificate'", max_length=200)),
                ('issuing_organization', models.CharField(help_text="e.g., 'Google', 'Coursera', 'University'", max_length=100)),
                ('issue_date', models.DateField()),
                ('expiry_date', models.DateField(blank=True, help_text='Leave blank if no expiry', null=True)),
                ('credential_url', models.URLField(blank=True, help_text='Link to verify credential', null=True)),
                ('credential_id', models.CharField(blank=True, help_text='Certificate ID/License number', max_length=100, null=True)),
                ('certificate_file', models.FileField(blank=True, help_text='Upload certificate (PDF, JPG, PNG)', null=True, upload_to='certificates/%Y/%m/%d/')),
                ('description', models.TextField(blank=True, help_text='Additional details about the certification', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='useraccount.userprofile')),
            ],
            options={
                'ordering': ['-issue_date'],
            },
        ),
    ]
