# Generated by Django 6.0 on 2026-05-02 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0011_certification'),
        ('useraccount', '0012_connectionrequest_delete_matchrequest'),
    ]

    operations = [
    ]
