# Generated by Django 6.0 on 2026-06-21 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0014_quiz_question'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='Quiz',
        ),
    ]
