# Generated by Django 6.0 on 2026-06-27 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0016_englishquiz_englishquestion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='englishquestion',
            name='quiz',
        ),
        migrations.DeleteModel(
            name='EnglishQuiz',
        ),
    ]
