# Generated by Django 6.0 on 2026-08-13 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Subscription', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='duration_days',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='discount_percentage',
            field=models.IntegerField(default=0, help_text='Discount percentage for this plan'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Subscription.subscriptionplan'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='duration_days',
            field=models.IntegerField(choices=[(30, '1 Month'), (90, '3 Months'), (180, '6 Months'), (365, '12 Months')], default=30),
        ),
    ]
