# Generated by Django 6.0 on 2026-08-13 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Subscription', '0002_payment_duration_days_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='discount_percentage',
        ),
    ]
