# Generated by Django 6.0 on 2026-08-15 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Subscription', '0003_remove_subscriptionplan_discount_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='admin_notes',
            field=models.TextField(blank=True, help_text='Admin notes for this payment'),
        ),
        migrations.AddField(
            model_name='payment',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes from user'),
        ),
        migrations.AddField(
            model_name='payment',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('kbz_pay', 'KBZ Pay'), ('wave_pay', 'Wave Pay'), ('bank_transfer', 'Bank Transfer'), ('aya_pay', 'AYA Pay'), ('cb_pay', 'CB Pay')], max_length=50),
        ),
        migrations.AlterField(
            model_name='payment',
            name='screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='payments/screenshots/%Y/%m/%d/'),
        ),
    ]
