# Generated by Django 6.0 on 2026-04-26 09:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('post_type', models.CharField(choices=[('study', 'Study Partner'), ('skill', 'Skill Swap')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('interested', models.ManyToManyField(blank=True, related_name='interested_posts', to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(blank=True, related_name='liked_posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
