# Generated by Django 6.0.3 on 2026-04-25 08:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedview', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchrequest',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedview_received_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='matchrequest',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedview_sent_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
