# Generated by Django 6.0 on 2026-04-28 15:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedview', '0003_post_image_post_post_type_post_video_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchrequest',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_received_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='matchrequest',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_sent_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
