# Generated by Django 6.0.4 on 2026-05-12 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedview', '0004_alter_matchrequest_receiver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('skill_swap', 'Skill Swap'), ('study_partner', 'Study Partner')], default='skill_swap', max_length=20),
        ),
        migrations.AddField(
            model_name='post',
            name='hashtags',
            field=models.CharField(blank=True, help_text='Comma separated: #tech,#python', max_length=200),
        ),
        migrations.AddField(
            model_name='post',
            name='topic',
            field=models.CharField(choices=[('language', 'Language'), ('tech', 'Technology'), ('science', 'Science'), ('art', 'Art'), ('business', 'Business'), ('general', 'General')], default='general', max_length=20),
        ),
    ]
