# Generated by Django 6.0 on 2026-05-18 12:12

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('feedview', '0006_post_is_edited_post_updated_at_comment_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='message',
            field=models.CharField(max_length=255, default=''),
        ),
    ]