# Generated by Django 6.0 on 2026-05-23 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedview', '0008_alter_comment_options_comment_parent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
