# Generated by Django 6.0.4 on 2026-05-15 12:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyroom', '0003_roomactivitylog_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='classwork',
            name='resource_file',
            field=models.FileField(blank=True, null=True, upload_to='classwork_resources/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'ppt', 'pptx', 'jpg', 'png', 'zip'])]),
        ),
        migrations.AddField(
            model_name='classwork',
            name='resource_link',
            field=models.URLField(blank=True, help_text='Optional external link', null=True),
        ),
        migrations.AddField(
            model_name='classwork',
            name='resource_title',
            field=models.CharField(blank=True, help_text='Title for the resource', max_length=200, null=True),
        ),
    ]
