# Generated by Django 6.0.4 on 2026-05-18 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyroom', '0005_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='classwork',
            name='content_type',
            field=models.CharField(choices=[('assignment', 'Assignment'), ('material', 'Material'), ('quiz', 'Quiz')], default='assignment', max_length=20),
        ),
    ]
