# Generated by Django 6.0 on 2026-08-13 04:00
# Generated by Django 6.0.7 on 2026-08-17 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyroom', '0008_scheduledcall'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledcall',
            name='jitsi_room_id',
            field=models.CharField(default='aO5ce5f8E_5P-gPliudQoQ', max_length=50, unique=True),
            field=models.CharField(default='seAoe9SBoaQx1mQuwEM5TQ', max_length=50, unique=True),
        ),
    ]
