# Generated by Django 6.0.4 on 2026-08-17 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyroom', '0009_alter_scheduledcall_jitsi_room_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledcall',
            name='jitsi_room_id',
            field=models.CharField(default='Qx7mSYz9gqwFxIAbbYhUSA', max_length=50, unique=True),
        ),
    ]
