# Generated by Django 6.0 on 2026-08-13 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyroom', '0009_alter_scheduledcall_jitsi_room_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyroom',
            name='max_members',
            field=models.IntegerField(default=3, help_text='Maximum number of members allowed (3 for free, 999 for premium)'),
        ),
        migrations.AlterField(
            model_name='scheduledcall',
            name='jitsi_room_id',
            field=models.CharField(default='HWHNCiOXPX-zxviiet8Xfg', max_length=50, unique=True),
        ),
    ]
