# Generated by Django 6.0 on 2026-08-15 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyroom', '0010_studyroom_max_members_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledcall',
            name='jitsi_room_id',
            field=models.CharField(default='_x5kgPDJQkgllFn6cpsFSw', max_length=50, unique=True),
        ),
    ]
