# Generated by Django 6.0 on 2026-08-15 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyroom', '0011_alter_scheduledcall_jitsi_room_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledcall',
            name='jitsi_room_id',
            field=models.CharField(default='EqZF84gi3b_jKS02PmHw5g', max_length=50, unique=True),
        ),
    ]
