# Generated by Django 6.0 on 2026-08-20 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studyroom', '0010_alter_scheduledcall_jitsi_room_id'),
        ('studyroom', '0012_alter_scheduledcall_jitsi_room_id'),
    ]

    operations = [
    ]
