# Generated by Django 4.2.30 on 2026-08-20 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyroom', '0013_merge_20260820_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledcall',
            name='jitsi_room_id',
            field=models.CharField(default='KTBKFO3iWwFHd17Cietasw', max_length=50, unique=True),
        ),
    ]
